### ISSUE TITLE
weird error message and possibly related vector-index (?) corruption afterwards

### ISSUE THREAD

**Issue by krskrs** [weaviate/weaviate#4227]
### How to reproduce this bug?

delete all records from a tenant with a  query like 
```python
{"match": {"class": weaviate_class, "where": {"path": ["title"], "operator": "NotEqual", "valueText": "__kttGNcJ890_"}}}
```
where the valueText NotEqual to a dummy value has the aim of selecting all records

Then, immediately after the delete operation (done via REST call) successfully returns, we insert a batch of documents w/ vectors in the tenant (about 10 documents), via `/v1/batch/objects`.

Then immediately after, we start getting this error (please note it doesn't happen always) when querying in vector mode:

`explorer: get class: vector search: object vector search at index xxxxxx: shard xxxxxxxx: vector search: entrypoint was deleted in the object store, it has been flagged for cleanup and should be fixed in the next cleanup cycle`

Then after something like a minute, vector queries will start working again BUT they won't return all results, but only one single document. Ie: let's take a query with a limit of 4, which is expected to always return 4 documents, it will return only 1 document. BM25 queries on the contrary would return 4 documents, from the same tenant. Some other times we have also seen duplicate results from vector queries, instead of one single document.

*PLEASE NOTE THIS BEHAVIOR DON'T OCCUR SYSTEMATICALLY, I mean that after the delete-insert procedure, sometimes everything goes smoothly and in this case subsequent vector searches will be always fine. On the contrary, when something goes wrong with delete-insert, vector searches will always present issues (be them duplicate documents, or only one document returned, etc.).

### What is the expected behavior?

all records are deleted, new records are inserted, no errors are returned on immediate queries and vector queries work normally.

### What is the actual behavior?

we get an error on querying after delete-insert, and when the error resolves, vector searches show a weird behavior.

### Server Version

1.23.7 on your cloud servoce weaviate.cloud

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by etiennedi** [comment]
Thanks for the report. Could you add a small reproducing script? That would help us quite a bit to get to a speedy solution. Thanks!

**Comment by krskrs** [comment]
Hi @etiennedi, I do undestand that this is a weird/annoying issue to analyze and debug, but at the same time, I have not a ready standalone script, as we're experiencing this situation in our commercial product, when we import some kb.

So, let's see how we can find the quickest way to get to the bottom of it.

I believe the straightest way for reproducing what we do would be to create a class with multi-tenant, and insert from 10 to 20 random documents with vectors with the following structure, with meta_data and meta_keys 

```JSON
{
    "class": "Test",
    "invertedIndexConfig": {
        "bm25": {
            "b": 0.75,
            "k1": 1.2
        },
        "cleanupIntervalSeconds": 60,
        "stopwords": {
            "additions": null,
            "preset": "en",
            "removals": null
        }
    },
    "multiTenancyConfig": {
        "enabled": true
    },
    "properties": [
        {
            "dataType": [
                "text"
            ],
            "indexFilterable": true,
            "indexSearchable": true,
            "name": "text",
            "tokenization": "word"
        },
        {
            "dataType": [
                "text"
            ],
            "indexFilterable": true,
            "indexSearchable": false,
            "name": "title",
            "tokenization": "word"
        },
        {
            "dataType": [
                "int"
            ],
            "indexFilterable": false,
            "indexSearchable": false,
            "name": "n"
        },
        {
            "dataType": [
                "text"
            ],
            "indexFilterable": false,
            "indexSearchable": false,
            "name": "meta_data",
            "tokenization": "word"
        },
        {
            "dataType": [
                "text"
            ],
            "indexFilterable": true,
            "indexSearchable": true,
            "name": "meta_keys",
            "tokenization": "word"
        }
    ],
    "replicationConfig": {
        "factor": 1
    },
    "shardingConfig": {
        "virtualPerPhysical": 0,
        "desiredCount": 0,
        "actualCount": 0,
        "desiredVirtualCount": 0,
        "actualVirtualCount": 0,
        "key": "",
        "strategy": "",
        "function": ""
    },
    "vectorIndexConfig": {
        "skip": false,
        "cleanupIntervalSeconds": 300,
        "maxConnections": 64,
        "efConstruction": 128,
        "ef": -1,
        "dynamicEfMin": 100,
        "dynamicEfMax": 500,
        "dynamicEfFactor": 8,
        "vectorCacheMaxObjects": 1000000000000,
        "flatSearchCutoff": 40000,
        "distance": "cosine",
        "pq": {
            "enabled": false,
            "bitCompression": false,
            "segments": 0,
            "centroids": 256,
            "trainingLimit": 100000,
            "encoder": {
                "type": "kmeans",
                "distribution": "log-normal"
            }
        }
    },
    "vectorIndexType": "hnsw",
    "vectorizer": "none"
}
``` 

To insert documents we use somethink like:

```python
            embeddable_documents = [
                {"properties": {'text': record['text'], 'title': record['title'], 'n': record['tokens_count'],
                 'meta_keys': record['meta_keys']},
                 "vector": source_documents_embeddings[i]} for i, record in enumerate(kb_documents)]

            await save_documents(integration.get_weaviate_endpoint(), integration.get_weaviate_api_key(),
                                              index,
                                              embeddable_documents, name_space)
```

where save_documents is 

```python

    async def save_documents(self, url: str, api_key: str, weaviate_class: str, documents: list, name_space: str = ""):
        api_url = f"{url}/v1/batch/objects"

        objs = [{"class": weaviate_class, "tenant": name_space, "properties": d["properties"], "vector": d["vector"]} for d in documents]

        json_body = {"objects": objs}

        async with self.aio_http_client_session.post(api_url,
                                                     headers={"Authorization": f"Bearer {api_key}"}, json=json_body) as r:
```

then we delete such documents with a code like:

```python
    async def empty_namespace(self, url: str, api_key: str, weaviate_class: str, namespace: str, use_tenant: bool):
        api_url = f"{url}/v1/batch/objects?tenant={namespace}"
        query_body = {"match": {"class": weaviate_class, "where": {"path": ["title"], "operator": "NotEqual", "valueText": "__kttGNcJ890_"}}}

    async with self.aio_http_client_session.delete(api_url,
                                                       headers={
                                                           "Authorization": f"Bearer {api_key}"},
                                                       json=query_body) as r:

```

after deleting all documents, you should re-insert them back with the same code used for the first insertion, and at this time you should make a vector query, and see if you get the error `explorer: get class: vector search: object vector search at index xxxxxx: shard xxxxxxxx: vector search: entrypoint was deleted in the object store, it has been flagged for cleanup and should be fixed in the next cleanup cycle`.

I'm not sure on whether the error is related, but does it tell you anything? I mean such an error? I couldn't find much information around about it.

I tried to do my best to put together these snippets from our codebase, quite in a rush, but if it might be of more help, we can also follow up on the support ticket I have opened, and maybe I can manage to give you access to a real reproduction.

**Comment by etiennedi** [comment]
Thanks, that's already super helpful. We can work with this.

**Comment by krskrs** [comment]
Hi, would it be possible to have an idea of the timeline for handling this? It's causing some nuisances in our production environment on weaviate cloud. Even some updates would be useful as we've closed our ticket with support in favor of this issue.

**Comment by krskrs** [comment]
@etiennedi hello again, today we updated a collection and it just happened again. After deleting all records, we got 

`vector search: object vector search at index zzzzz: shard xxx_available_courses: vector search: entrypoint was deleted in the object store, it has been flagged for cleanup and should be fixed in the next cleanup cycle`

after a couple minutes the error stopped, and this time we are getting duplicate documents from vector queries (documents deleted from the delete operation and documents inserted in the subsequent insert operation).

Please let us know when we might expect any updates on this. Although we've switched to this issue on github, this started as a support ticket. We are a paying customer.

**Comment by rthiiyer82** [comment]
@krskrs : Apologies , for the delay in getting back to you. 

We have been trying to reproduce the issue you mentioned above but haven't been successful. I have tried the following steps:
1. Create a class
2. Insert objects
3. Delete all the objects inserted in the above steps
4. Reinsert the objects that was deleted
5. Perform vector search 

The error you mentioned sounds like a tombstone clean up error. Recently, we have fixed few issues in Tombstone. Do you want to upgrade your cluster to latest weaviate version (1.24.4) and see if its still reproducible? 
Also, please can you share WCS cluster ID?

**Comment by krskrs** [comment]
Hi @rthiiyer82 apologies too for the delay in getting back from our side. We had updated to 1.24.4 just after your reply here, but since this issue doesn't occur on every delete/update cycle we do, and since we lately haven't been doing a lot of such cycles we haven't collected enough reliable information yet to follow up. Today, for example, the issue happened again, on 1.24.4, but it was on a tenant created with weaviate versions older than 1.24.4 and I don't know if this could make a difference or not. However, that tenant was in production and we couldn't leave it "corrupted" (it had started to return only 2 results w/ vector queries, while we were asking for 4. After deleting the tenant (instead of its records) and re-creating it, the issue was fixed as always).

This said, I take the chance to confirm that as soon as this happens again, on a tenant which can be 'left broken' I will be happy to get in touch and provide all the information so that you can investigate directly on the actual data.

Thank you.

**Comment by krskrs** [comment]
Although I'm still not able to provide a live broken index on the managed service, I'd also like to report that we're getting these errors quite often: "vector search: entrypoint was deleted in the object store, it has been flagged for cleanup and should be fixed in the next cleanup cycle" .. Can you explain what this error exactly means, and even more important, if it's normal for it to happen in some cases? And if so, in which cases? Sometimes, after we delete and insert records, our production deployments give errors of this type. Since we're on the managed service, there's no much we can do about it (ie: parameters to adjust). Can you please provide some more info on this? Most likely this is also related to the corruption we're seeing.

**Comment by andrewisplinghoff** [comment]
We ran into the same issue, using Weaviate 1.25.8.

**Comment by dirkkul** [comment]
Hello! We did a lot of fixes to handling deletes of entrypoints in the last months - does this still occur on the latest releases?

**Comment by dudanogueira** [comment]
Closing as lot has changed. If you face similar issue, please, open a new one and make sure to reproduce on latest.
Thanks!
